lang: pt_BR
locale: pt_BR
title: "&copy; 2013-2020 Alan Cândido"
email: brodao@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
     Sítio pessoal com meus projetos em várias áreas. Programação, Eletrônica, Arduino, Marcenaria, entre outras.
tagline: Sítio pessoal com meus projetos em várias áreas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: "Alan Cândido <brodao@gmail.com>"
github_username: brodao
google_analytics: "UA-42484916-1"
#incremental: true

# Build settings
#theme: minima
#theme: jekyll-theme-minimal
#remote_theme: "manid2/lone-wolf-theme"
#remote_theme: "matrixfox/jekyll-theme-bootstrap"
plugins:
  - jekyll-feed
  - jekyll-include-cache

collections:
  left_side:
    output: true

# defaults:
#   -
#     scope:
#       type: "left_side"
#     values:
#      layout: "call"
